# analysis.py
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# ensure consistent plotting behaviour
sns.set(style="whitegrid")
plt.rcParams["figure.dpi"] = 120

DATA_PATH = "data/waste_data.csv"
FIG_DIR = "outputs/figures"
SUMMARY_DIR = "outputs"

def prepare_dirs():
    os.makedirs(FIG_DIR, exist_ok=True)
    os.makedirs(SUMMARY_DIR, exist_ok=True)

def load_data(path=DATA_PATH):
    if not os.path.exists(path):
        raise FileNotFoundError(f"Data file not found. Run generate_data.py first. Expected at: {path}")
    df = pd.read_csv(path, parse_dates=["date"])
    return df

def basic_checks(df):
    print("Rows, Columns:", df.shape)
    print("\nData types:")
    print(df.dtypes)
    print("\nMissing values:")
    print(df.isnull().sum())
    print("\nSummary stats:")
    print(df["waste_generated_kg"].describe())

def zone_average_plot(df):
    avg_by_zone = df.groupby("zone")["waste_generated_kg"].mean().reset_index().sort_values("waste_generated_kg", ascending=False)
    plt.figure(figsize=(8,5))
    sns.barplot(data=avg_by_zone, x="zone", y="waste_generated_kg")
    plt.title("Average Waste Generated by Zone (kg/day)")
    plt.ylabel("Average waste (kg)")
    plt.xlabel("Zone")
    plt.tight_layout()
    out = os.path.join(FIG_DIR, "avg_waste_by_zone.png")
    plt.savefig(out)
    plt.close()
    print("Saved:", out)

def monthly_trend_plot(df):
    df["month"] = df["date"].dt.month
    monthly = df.groupby("month")["waste_generated_kg"].sum().reset_index()
    plt.figure(figsize=(9,4))
    sns.lineplot(data=monthly, x="month", y="waste_generated_kg", marker="o")
    plt.title("Monthly Waste Generation Trend (Total kg)")
    plt.xlabel("Month")
    plt.xticks(range(1,13))
    plt.ylabel("Total waste (kg)")
    plt.tight_layout()
    out = os.path.join(FIG_DIR, "monthly_trend.png")
    plt.savefig(out)
    plt.close()
    print("Saved:", out)

def zone_month_heatmap(df):
    df["month"] = df["date"].dt.month
    pivot = df.groupby(["zone","month"])["waste_generated_kg"].mean().unstack()
    plt.figure(figsize=(10,4))
    sns.heatmap(pivot, annot=True, fmt=".1f", cmap="YlGnBu")
    plt.title("Average Waste (kg/day) — Zone vs Month")
    plt.xlabel("Month")
    plt.ylabel("Zone")
    plt.tight_layout()
    out = os.path.join(FIG_DIR, "zone_month_heatmap.png")
    plt.savefig(out)
    plt.close()
    print("Saved:", out)

def save_summary(df):
    # key metrics
    summary = {
        "total_waste_kg": float(df["waste_generated_kg"].sum()),
        "avg_daily_waste_kg": float(df.groupby("date")["waste_generated_kg"].sum().mean()),
        "max_single_day_waste_kg": float(df["waste_generated_kg"].max()),
        "min_single_day_waste_kg": float(df["waste_generated_kg"].min())
    }
    summary_df = pd.DataFrame.from_dict(summary, orient="index", columns=["value"])
    out = os.path.join(SUMMARY_DIR, "summary_metrics.csv")
    summary_df.to_csv(out)
    print("Saved summary metrics:", out)

def main():
    prepare_dirs()
    df = load_data()
    basic_checks(df)
    zone_average_plot(df)
    monthly_trend_plot(df)
    zone_month_heatmap(df)
    save_summary(df)
    print("\nAll done. Figures in", FIG_DIR)

if __name__ == "__main__":
    main()
